[build]
  publish = ".next"
  command = "npm run build"

[functions]
  included_files = ["hud-wrapper"]

[functions.environment]
  AWS_LAMBDA_EXEC_WRAPPER = "./hud-wrapper"

[functions.node_bundler]
  external = ["hud-sdk"]