[build]
  publish = ".next"
  command = "npm run build"

[functions]
  included_files = ["hud-wrapper"]
  node_bundler = "esbuild"
  external_node_modules = ["hud-sdk"]
  included_files = ["node_modules/hud-sdk/**","/var/task/node_modules/hud-sdk/**"]
